create table weather_forecast(
    id          int primary key generated by default as identity,
    day         date,
    timesOfDay  varchar(50),
    temp        varchar(50),
    weather     varchar(50),
    pressure    varchar(50),
    humidity    varchar(50),
    windSpeed   varchar(50),
    felt        varchar(50),
    city        varchar(50)
);

create table users (
    chatId     bigint primary key,
    username   varchar(50),
    city       varchar(50),
    first_name varchar(50),
    last_name  varchar(50),
    platform   varchar(50)
);
